# Generated by Django 4.1.5 on 2023-01-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='poster',
            field=models.BooleanField(default=False),
        ),
    ]
